// ກຄຂງຈສຊຍດຕຖທນບປຜຝພຟມຢຣລວຫອຮໝໜ
const consonants: any = {
	ກ: { leading: { en: 'k', fr: 'k', ph: 'k' }, trailing: { en: 'k', fr: 'k', ph: 'k' } },
	ຄ: { leading: { en: 'kh', fr: 'kh', ph: 'kʰ' } },
	ຂ: { leading: { en: 'kh', fr: 'kh', ph: 'kʰ' } },
	ງ: { leading: { en: 'ng', fr: 'ng', ph: 'ŋ' }, trailing: { en: 'ng', fr: 'ng', ph: 'ŋ' } },
	ຈ: { leading: { en: 'ch', fr: 'tj', ph: 'tɕ' } },
	ສ: { leading: { en: 's', fr: 's', ph: 's' } },
	ຊ: { leading: { en: 's', fr: 's', ph: 's' } },
	ຍ: { leading: { en: 'ny', fr: 'ny', ph: 'ɲ' }, trailing: { en: 'i', fr: 'y', ph: 'ɲ' } },
	ດ: { leading: { en: 'd', fr: 'd', ph: 'd' }, trailing: { en: 'd', fr: 't', ph: 'd' } },
	ຕ: { leading: { en: 't', fr: 't', ph: 't' } },
	ຖ: { leading: { en: 'th', fr: 'th', ph: 'tʰ' } },
	ທ: { leading: { en: 'th', fr: 'th', ph: 'tʰ' } },
	ນ: { leading: { en: 'n', fr: 'n', ph: 'n' }, trailing: { en: 'n', fr: 'n', ph: 'n' } },
	ບ: { leading: { en: 'b', fr: 'b', ph: 'b' }, trailing: { en: 'b', fr: 'p', ph: 'b' } },
	ປ: { leading: { en: 'p', fr: 'p', ph: 'p' } },
	ຜ: { leading: { en: 'ph', fr: 'ph', ph: 'pʰ' } },
	ຝ: { leading: { en: 'f', fr: 'f', ph: 'f' } },
	ພ: { leading: { en: 'ph', fr: 'ph', ph: 'pʰ' } },
	ຟ: { leading: { en: 'f', fr: 'f', ph: 'f' } },
	ມ: { leading: { en: 'm', fr: 'm', ph: 'm' }, trailing: { en: 'm', fr: 'm', ph: 'm' } },
	ຢ: { leading: { en: 'y', fr: 'y', ph: 'j' } },
	ຣ: { leading: { en: 'l', fr: 'l', ph: 'r' } },
	ລ: { leading: { en: 'l', fr: 'l', ph: 'l' } },
	ວ: { leading: { en: 'v', fr: 'v', ph: 'ʋ' }, trailing: { en: 'w', fr: 'w', ph: 'w' } },
	ອ: { leading: { en: '', fr: '', ph: 'ʔ' } },
	ຫ: { leading: { en: 'h', fr: 'h', ph: 'h' } },
	ຮ: { leading: { en: 'h', fr: 'h', ph: 'h' } },
	ໝ: { leading: { en: 'm', fr: 'm', ph: 'm' } },
	ໜ: { leading: { en: 'n', fr: 'n', ph: 'n' } },
	ຫງ: { leading: { en: 'ng', fr: 'ng', ph: 'ŋ' } },
	ຫຍ: { leading: { en: 'ny', fr: 'ny', ph: 'ɲ' } },
	ຫນ: { leading: { en: 'n', fr: 'n', ph: 'n' } },
	ຫມ: { leading: { en: 'm', fr: 'm', ph: 'm' } },
	ຫຼ: { leading: { en: 'l', fr: 'l', ph: 'l' } },
	ຫລ: { leading: { en: 'l', fr: 'l', ph: 'l' } },
	ຫວ: { leading: { en: 'v', fr: 'v', ph: 'ʋ' } }
};
export { consonants };
